name: kitchen_studio_10162023
description: A kitchen studio project for the volume system
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dart_ping: ^9.0.1
  audioplayers: ^0.20.1
  flutter_charts: ^0.5.2
  gauge_indicator: ^0.4.3
  easy_stepper: ^0.8.1
  tcp_socket_connection: ^0.3.1
  udp: ^5.0.3
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  window_manager: ^0.2.7
  cupertino_icons: ^1.0.2
  sqflite_common_ffi: ^2.3.0+2
  file_picker: ^6.0.0
  path: ^1.8.3
  avatar_glow: ^2.0.2
  carousel_slider: ^4.2.1
  web_socket_channel: ^2.0.0
  shelf_web_socket: ^1.0.4
  typed_data: ^1.3.0
  path_provider: ^2.1.1
  flutter_blockly: ^1.2.0
  timelines: ^0.1.0
  flutter_draggable_gridview: ^0.0.8
  flutter_staggered_grid_view: ^0.7.0
  syncfusion_flutter_gauges: ^24.1.46
  syncfusion_flutter_sliders: ^24.1.46
  numberpicker: ^2.1.2
  flutter_picker: ^2.1.0
  shelf_static: ^1.1.2
  shelf: ^1.4.1
  url_launcher: ^6.2.5
  webview_windows: ^0.4.0
  kitchen_module:
    path: packages/kitchen_module
  dummy_module:
    path: packages/dummy_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

scripts:
  move-web: xcopy web\* .\build\windows\x64\runner\Release /s /e /y

#  flutter build windows && flutter pub run move-web