name: kitchen_module
description: Dart package which manages the arduino udp communication.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tcp_socket_connection: ^0.3.1
  udp: ^5.0.3
  sqflite_common_ffi: ^2.3.0+2
  web_socket_channel: ^2.0.0
  shelf: ^1.0.0
  shelf_web_socket: ^1.0.4
  typed_data: ^1.3.0
  cache:
    path: ../cache
  database_service:
    path: ../database_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7